# GitHub Expert - Sphinx Configuration
# ===================================================

from datetime import datetime

# -- Project information -----------------------------------------------------

project = 'GitHub 专家指南'
author = 'your_name'
copyright = f'{datetime.now().year}, {author}'

# The short X.Y version
version = '0.1'
# The full version, including alpha/beta/rc tags
release = '0.1'

# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.todo',
    'sphinx.ext.extlinks',
    'sphinx.ext.intersphinx',
    'sphinxcontrib.mermaid',
]

# -- Mermaid configuration ---------------------------------------------------

mermaid_output_format = 'raw'  # 在 RTD 上也能正常渲染

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'collapse_navigation': False,
    'navigation_depth': 3,
}
html_static_path = ['_static']
html_css_files = ['custom.css']

# -- Options for autosectionlabel --------------------------------------------

autosectionlabel_prefix_document = True

# -- Options for todo extension ----------------------------------------------

todo_include_todos = True

# -- Source file suffix ------------------------------------------------------

source_suffix = {
    '.rst': 'restructuredtext',
}

# -- Intersphinx mapping -----------------------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'git': ('https://git-scm.com/docs', None),
}